# Galapix - an image viewer for large image collections
# Copyright (C) 2018 Ingo Ruhnke <grumbel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

image: ubuntu:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get -qq update
  - apt-get -qq -y install lsb-release
  - lsb_release -a
  - apt-get -qq -y install
    build-essential
    pkg-config
    cmake
    g++-8
    clang-6.0
    libfuse-dev
    libmhash-dev
    libminizip-dev
    zlib1g-dev
  # patch for mhash, see https://bugs.launchpad.net/ubuntu/+source/mhash/+bug/1465562
  - sed -i "s/_Bool/bool/" /usr/include/mutils/mutils.h

.build_template: &build
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWERROR=ON -DWARNINGS=ON -DBUILD_TESTS=ON
    - make VERBOSE=1 -k
    - cd ..
    - build/test_concat_fuse

build:gcc:release:
  <<: *build
  variables:
    CXX: g++-8
    BUILD_TYPE: Release

build:clang:release:
  <<: *build
  variables:
    CXX: clang++-6.0
    BUILD_TYPE: Release

build:gcc:debug:
  <<: *build
  variables:
    CXX: g++-8
    BUILD_TYPE: Debug

build:clang:debug:
  <<: *build
  variables:
    CXX: clang++-6.0
    BUILD_TYPE: Debug

# EOF #
